### ISSUE TITLE
Mapped ports only shown at the application level not under Docker Hosts/Containers

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#312]
Uncertain as to whether this is an issue, but observed the following.

Deploying a simple container app as follows:
```
location: my-docker-cloud
services:
- type: docker:nginx:latest
  name: nginx
  openPorts:
  - 80
```
Results in the `VanillaDockerApplication` having a populated `mapped.docker.port.80` sensor.

The associated container under Docker Hosts/Docker Containers does not have a mapped port sensor.
