### ISSUE TITLE
VanillaDockerApps from hub images without id specified result in a non-unique container name

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#313]
If you deploy a VanillaDockerApp but don't supply an `id:` tag then the resulting container takes the name of the image being deployed which is non-unique thereby preventing additional instance of that app yaml being deployed.

For example:
```
location: my-docker-cloud
services:
- type: docker:nginx:latest
  name: nginx
  openPorts:
  - 80
```
results in the container called `nginx`, adding an `id: nginx` results in a unique container name `nginx_<entityid>`.
