### ISSUE TITLE
Attempting to add clocker.bom ERROR

### ISSUE THREAD

**Issue by naqsh01** [brooklyncentral/clocker#345]
Attempted to add clocker.bom following the instructions on http://www.clocker.io/tutorials/getting-started.html (Brookyn).

Get the following error: 
Remote catalog url classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom can't be fetched.: Error getting resource 'classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom' for classload:[OSGi:<catalog url reference loader>:0.0.0[[CatalogBundleDto{symbolicName=null, version=null, url=https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.brooklyn.etcd&a=brooklyn-etcd&v=2.3.0-SNAPSHOT}, CatalogBundleDto{symbolicName=null, version=null, url=https://oss.sonatype.org/service/local/repositories/releases/content/io/brooklyn/clocker/common/2.0.0/common-2.0.0.jar}, CatalogBundleDto{symbolicName=null, version=null, url=https://oss.sonatype.org/service/local/repositories/releases/content/io/brooklyn/clocker/swarm/2.0.0/swarm-2.0.0.jar}, CatalogBundleDto{symbolicName=null, version=null, url=https://oss.sonatype.org/service/local/repositories/releases/content/io/brooklyn/clocker/kubernetes/2.0.0/kubernetes-2.0.0.jar}]]];[java:AggregateClassLoader[AggregateClassLoader[sun.misc.Launcher$AppClassLoader@15aeb7ab, AggregateClassLoader[], AggregateClassLoader[AggregateClassLoader[AggregateClassLoader[org.apache.brooklyn.util.javalang.LoadedClassLoader@3d68e542], AggregateClassLoader[]]]]]]: IOException: Error accessing classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom: java.io.IOException: io.brooklyn.clocker.swarm:swarm/swarm.bom not found on classpath

**Comment by tbouron** [comment]
Hi @naqsh01. Did you downloaded the 4 JARs of the step 2 and put them into the `lib/dropins` folder of your Brooklyn install?

**Comment by tbouron** [comment]
Also, which `clocker.bom` are you using? The one for Brooklyn is a bit different and dowloaded from step 3 => http://www.clocker.io/clocker.bom

**Comment by naqsh01** [comment]
I placed the jars under libs/dropins.

Should I have renamed brooklyn-etcd from the original filename?

I used this one (from.doc)
http://www.clocker.io/clocker.bom

I also copied the section from.thr readme.

Thanks,
Aliusa

**Comment by naqsh01** [comment]
Just to add.

I started Brooklyn like:


./bin/brooklyn launch

**Comment by tbouron** [comment]
Hey @naqsh01, that's very strange, we tested it multiple times to make sure it ran smoothly. Something occurred to me but which version of Brooklyn do you use?

In a meantime, we are going through the instructions to see if we miss something.

**Comment by naqsh01** [comment]
Version:  0.10.0-20160930.1659

I grabbed the brooklyn from: 
http://download.cloudsoft.io/brooklyn/0.10.0-20160930.1659/brooklyn-dist-0.10.0-20160930.1659-dist.tar.gz

How can I verify the jar files were picked up?

9/brooklyn-dist-0.10.0-20160930.1659/lib/dropins$ ls -kl
total 108
-rw-rw-r-- 1 aliusa aliusa 45761 Aug 30 23:48 brooklyn-etcd-2.3.0-20160831.034817-11.jar
-rw-rw-r-- 1 aliusa aliusa 18783 Oct  3 06:43 common-2.0.0.jar
-rw-rw-r-- 1 aliusa aliusa 18783 Oct  3 06:43 kubernetes-2.0.0.jar
-rw-rw-r-- 1 aliusa aliusa 18783 Oct  3 06:43 swarm-2.0.0.jar

**Comment by tbouron** [comment]
So I think we found the issue @naqsh01. Can you try with this clocker.bom file?
```yaml
brooklyn.catalog:
  items:
    - classpath://io.brooklyn.etcd.brooklyn-etcd:brooklyn-etcd/catalog.bom
    - classpath://io.brooklyn.clocker.common:common/common.bom
    - classpath://io.brooklyn.clocker.common:docker/docker.bom
    - classpath://io.brooklyn.clocker.common:main/catalog.bom
    - classpath://io.brooklyn.clocker.swarm:swarm/swarm.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/plugins.bom
    - classpath://io.brooklyn.clocker.kubernetes:kubernetes/kubernetes.bom
```
