### ISSUE TITLE
Single Docker VM on Clocker 1.1.1 fails on AWS

### ISSUE THREAD

**Issue by grkvlt** [brooklyncentral/clocker#360]
This blueprint should create a single VM docker cloud, but fails due to errors with the configuration.
```
services:
  - type: 'docker-cloud-single:1.1.1'
    brooklyn.config:
      entity.dynamicLocation.name: DockerEngineSingle
      docker.host.cluster.initial.size: 1
      docker.registry.start: true
      docker.version: 1.10.3
```
